PREFIX    = $(DEVKITARM)/bin/arm-none-eabi
CC        = $(PREFIX)-gcc
CXX       = $(PREFIX)-g++
AR        = $(PREFIX)-ar

#SRCS+=./common/stdc++compat.cpp
SRCS+=./dlls/airtank.cpp
SRCS+=./dlls/ammo.cpp
SRCS+=./dlls/animating.cpp
SRCS+=./dlls/animation.cpp
SRCS+=./dlls/basemonster.cpp
SRCS+=./dlls/bmodels.cpp
SRCS+=./dlls/buttons.cpp
SRCS+=./dlls/career_tasks.cpp
SRCS+=./dlls/cbase.cpp
SRCS+=./dlls/client.cpp
SRCS+=./dlls/cmdhandler.cpp
SRCS+=./dlls/combat.cpp
SRCS+=./dlls/debug.cpp
SRCS+=./dlls/doors.cpp
SRCS+=./dlls/effects.cpp
SRCS+=./dlls/explode.cpp
SRCS+=./dlls/func_break.cpp
SRCS+=./dlls/func_tank.cpp
SRCS+=./dlls/game.cpp
SRCS+=./dlls/gamerules.cpp
SRCS+=./dlls/ggrenade.cpp
SRCS+=./dlls/gib.cpp
SRCS+=./dlls/globals.cpp
SRCS+=./dlls/healthkit.cpp
SRCS+=./dlls/hintmessage.cpp
SRCS+=./dlls/h_battery.cpp
SRCS+=./dlls/h_cycler.cpp
SRCS+=./dlls/h_export.cpp
SRCS+=./dlls/items.cpp
SRCS+=./dlls/lights.cpp
SRCS+=./dlls/mapinfo.cpp
SRCS+=./dlls/maprules.cpp
SRCS+=./dlls/mortar.cpp
SRCS+=./dlls/multiplay_gamerules.cpp
SRCS+=./dlls/observer.cpp
SRCS+=./dlls/pathcorner.cpp
SRCS+=./dlls/plats.cpp
SRCS+=./dlls/player.cpp
SRCS+=./dlls/revert_saved.cpp
SRCS+=./dlls/saverestore.cpp
SRCS+=./dlls/singleplay_gamerules.cpp
SRCS+=./dlls/skill.cpp
SRCS+=./dlls/sound.cpp
SRCS+=./dlls/soundent.cpp
SRCS+=./dlls/spectator.cpp
SRCS+=./dlls/subs.cpp
SRCS+=./dlls/training_gamerules.cpp
SRCS+=./dlls/triggers.cpp
SRCS+=./dlls/tutor.cpp
SRCS+=./dlls/tutor_base_states.cpp
SRCS+=./dlls/tutor_base_tutor.cpp
SRCS+=./dlls/tutor_cs_states.cpp
SRCS+=./dlls/tutor_cs_tutor.cpp
SRCS+=./dlls/util.cpp
SRCS+=./dlls/vehicle.cpp
SRCS+=./dlls/weapons.cpp
SRCS+=./dlls/weapontype.cpp
SRCS+=./dlls/world.cpp
SRCS+=./dlls/addons/item_airbox.cpp
SRCS+=./dlls/addons/point_command.cpp
SRCS+=./dlls/addons/trigger_random.cpp
SRCS+=./dlls/addons/trigger_setorigin.cpp
SRCS+=./dlls/API/CAPI_Impl.cpp
SRCS+=./dlls/API/CSEntity.cpp
SRCS+=./dlls/API/CSPlayer.cpp
SRCS+=./dlls/API/CSPlayerItem.cpp
SRCS+=./dlls/bot/cs_bot.cpp
SRCS+=./dlls/bot/cs_bot_chatter.cpp
SRCS+=./dlls/bot/cs_bot_event.cpp
SRCS+=./dlls/bot/cs_bot_init.cpp
SRCS+=./dlls/bot/cs_bot_learn.cpp
SRCS+=./dlls/bot/cs_bot_listen.cpp
SRCS+=./dlls/bot/cs_bot_manager.cpp
SRCS+=./dlls/bot/cs_bot_nav.cpp
SRCS+=./dlls/bot/cs_bot_pathfind.cpp
SRCS+=./dlls/bot/cs_bot_radio.cpp
SRCS+=./dlls/bot/cs_bot_statemachine.cpp
SRCS+=./dlls/bot/cs_bot_update.cpp
SRCS+=./dlls/bot/cs_bot_vision.cpp
SRCS+=./dlls/bot/cs_bot_weapon.cpp
SRCS+=./dlls/bot/cs_gamestate.cpp
SRCS+=./dlls/bot/states/cs_bot_attack.cpp
SRCS+=./dlls/bot/states/cs_bot_buy.cpp
SRCS+=./dlls/bot/states/cs_bot_defuse_bomb.cpp
SRCS+=./dlls/bot/states/cs_bot_escape_from_bomb.cpp
SRCS+=./dlls/bot/states/cs_bot_fetch_bomb.cpp
SRCS+=./dlls/bot/states/cs_bot_follow.cpp
SRCS+=./dlls/bot/states/cs_bot_hide.cpp
SRCS+=./dlls/bot/states/cs_bot_hunt.cpp
SRCS+=./dlls/bot/states/cs_bot_idle.cpp
SRCS+=./dlls/bot/states/cs_bot_investigate_noise.cpp
SRCS+=./dlls/bot/states/cs_bot_move_to.cpp
SRCS+=./dlls/bot/states/cs_bot_plant_bomb.cpp
SRCS+=./dlls/bot/states/cs_bot_use_entity.cpp
SRCS+=./dlls/hostage/hostage.cpp
SRCS+=./dlls/hostage/hostage_improv.cpp
SRCS+=./dlls/hostage/hostage_localnav.cpp
SRCS+=./dlls/hostage/states/hostage_animate.cpp
SRCS+=./dlls/hostage/states/hostage_escape.cpp
SRCS+=./dlls/hostage/states/hostage_follow.cpp
SRCS+=./dlls/hostage/states/hostage_idle.cpp
SRCS+=./dlls/hostage/states/hostage_retreat.cpp
SRCS+=./dlls/wpn_shared/wpn_ak47.cpp
SRCS+=./dlls/wpn_shared/wpn_aug.cpp
SRCS+=./dlls/wpn_shared/wpn_awp.cpp
SRCS+=./dlls/wpn_shared/wpn_c4.cpp
SRCS+=./dlls/wpn_shared/wpn_deagle.cpp
SRCS+=./dlls/wpn_shared/wpn_elite.cpp
SRCS+=./dlls/wpn_shared/wpn_famas.cpp
SRCS+=./dlls/wpn_shared/wpn_fiveseven.cpp
SRCS+=./dlls/wpn_shared/wpn_flashbang.cpp
SRCS+=./dlls/wpn_shared/wpn_g3sg1.cpp
SRCS+=./dlls/wpn_shared/wpn_galil.cpp
SRCS+=./dlls/wpn_shared/wpn_glock18.cpp
SRCS+=./dlls/wpn_shared/wpn_hegrenade.cpp
SRCS+=./dlls/wpn_shared/wpn_knife.cpp
SRCS+=./dlls/wpn_shared/wpn_m249.cpp
SRCS+=./dlls/wpn_shared/wpn_m3.cpp
SRCS+=./dlls/wpn_shared/wpn_m4a1.cpp
SRCS+=./dlls/wpn_shared/wpn_mac10.cpp
SRCS+=./dlls/wpn_shared/wpn_mp5navy.cpp
SRCS+=./dlls/wpn_shared/wpn_p228.cpp
SRCS+=./dlls/wpn_shared/wpn_p90.cpp
SRCS+=./dlls/wpn_shared/wpn_scout.cpp
SRCS+=./dlls/wpn_shared/wpn_sg550.cpp
SRCS+=./dlls/wpn_shared/wpn_sg552.cpp
SRCS+=./dlls/wpn_shared/wpn_smokegrenade.cpp
SRCS+=./dlls/wpn_shared/wpn_tmp.cpp
SRCS+=./dlls/wpn_shared/wpn_ump45.cpp
SRCS+=./dlls/wpn_shared/wpn_usp.cpp
SRCS+=./dlls/wpn_shared/wpn_xm1014.cpp
SRCS+=./engine/unicode_strtools.cpp
#SRCS+=./extra/CSSDK/common/parsemsg.cpp
#SRCS+=./extra/CSSDK/engine/crc32c.cpp
#SRCS+=./extra/CSSDK/engine/sys_shared.cpp
#SRCS+=./extra/CSSDK/public/interface.cpp
#SRCS+=./extra/CSSDK/public/tier0/dbg.cpp
SRCS+=./game_shared/shared_util.cpp
SRCS+=./game_shared/voice_gamemgr.cpp
SRCS+=./game_shared/bot/bot.cpp
SRCS+=./game_shared/bot/bot_manager.cpp
SRCS+=./game_shared/bot/bot_profile.cpp
SRCS+=./game_shared/bot/bot_util.cpp
SRCS+=./game_shared/bot/nav_area.cpp
SRCS+=./game_shared/bot/nav_file.cpp
SRCS+=./game_shared/bot/nav_node.cpp
SRCS+=./game_shared/bot/nav_path.cpp
SRCS+=./pm_shared/pm_debug.cpp
SRCS+=./pm_shared/pm_math.cpp
SRCS+=./pm_shared/pm_shared.cpp
#SRCS+=./public/FileSystem.cpp
#SRCS+=./public/interface.cpp
#SRCS+=./public/MemPool.cpp
#SRCS+=./public/utlsymbol.cpp
#SRCS+=./public/tier0/dbg.cpp
SRCS+=./regamedll/classes_dummy.cpp
SRCS+=./regamedll/hookchains_impl.cpp
SRCS+=./regamedll/precompiled.cpp
SRCS+=./regamedll/public_amalgamation.cpp
SRCS+=./regamedll/regamedll.cpp
SRCS+=./regamedll/sse_mathfun.cpp
# SRCS+=./unittests/animation_tests.cpp
# SRCS+=./unittests/mathfun_tests.cpp
# SRCS+=./unittests/struct_offsets_tests.cpp
# SRCS+=./unittests/TestRunner.cpp
SRCS+=./version/version.cpp

OBJS = $(SRCS:.cpp=.o) $(SRCS_C:.c=.o)

INCLUDES = -I. -I./common -I./dlls -I./dlls/addons -I./dlls/API -I./dlls/bot -I./dlls/bot/states -I./dlls/hostage -I./dlls/hostage/states -I./dlls/wpn_shared -I./engine -I./game_shared -I./game_shared/bot -I./pm_shared -I./public -I./public/regamedll -I./public/regamedll/API -I./regamedll -I./version -I./external
DEFINES = -Dstricmp=strcasecmp -D_strnicmp=strncasecmp -Dstrnicmp=strncasecmp -D_snprintf=snprintf -DCLIENT_WEAPONS -D__3DS__ \
	-DREGAMEDLL_FIXES \
	-DBUILD_LATEST \
	-DREGAMEDLL_ADD \
	-DREGAMEDLL_API \
	-DUNICODE_FIXES \
	-DCLIENT_WEAPONS \
	-DUSE_QSTRING \
	-DGNUC \
	-DPOSIX \
	-D_stricmp=strcasecmp \
	-D_strnicmp=strncasecmp \
	-D_strdup=strdup \
	-D_unlink=unlink \
	-D_vsnprintf=vsnprintf \
	-D_write=write \
	-D_close=close \
	-D_access=access \
	-D_vsnwprintf=vswprintf
CFLAGS =  -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O2 -Wl,-q -Wfatal-errors -Wno-write-strings -fsigned-char -fno-short-enums -ffunction-sections -fdata-sections  $(DEFINES) $(INCLUDES)
CXXFLAGS = $(CFLAGS) -fno-exceptions -std=gnu++14 -fno-threadsafe-statics -fpermissive -static-libstdc++ -static-libgcc
ASFLAGS = $(CFLAGS)

all: libserver.a

libserver.a: $(OBJS)
	$(AR) rcs $@ $^

clean:
	@rm -rf libserver.a $(OBJS)

$(DEPSDIR):
	@mkdir -p $@